apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-product
  name: mongo-product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-product
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-product
    spec:
      containers:
        - image: mongo:4.4.14-rc0-focal
          name: mongo-product
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-product-claim0
      volumes:
        - name: mongo-product-claim0
          persistentVolumeClaim:
            claimName: mongo-product-claim0
status: {}
