apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-inventory
  name: mysql-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-inventory
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-inventory
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: inventory-service
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:5.7
          name: mysql-inventory
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-inventory-claim0
      volumes:
        - name: mysql-inventory-claim0
          persistentVolumeClaim:
            claimName: mysql-inventory-claim0
status: {}
